---
- name: Generate a hosts file
  hosts: all
  become: true
  tasks:

    - name: Download the hosts.j2
      ansible.builtin.get_url:
        url: http://rhgls.labx.example.com/materials 
        dest: /home/automation/plays_2/hosts.j2
      ignore_errors: true

    - name: Generate the host file on test group
      ansible.builtin.template:
        src: /home/automation/plays_2/hosts.j2
        dest: /etc/myhosts
      when: inventory_hostname in groups['test']    

