---
- name: Configure the chronyd server
  hosts: all
  become: true
  vars:
    timesync_ntp_servers:
      - hostname: rhel.server.ntp.org
        iburst: true

  roles:
    - rhel-system-roles.timesync    

