---
- name: create groups and  users
  hosts: all
  become: true
  vars_files:
    - /home/automation/plays_2/locker.yml
    - user_list.yml

  tasks:
    - name: download the user file
      ansible.builtin.get_url:
        url: http://rhgls.labx.example.com/materials
        dest: /home/automation/plays/new_user_list.yml
        mode: 0644
      ignore_errors: true    

    - name: create suplementary group
      ansible.builtin.group:
        name: devops
        state: present
      when: inventory_hostname in groups['test'] or inventory_hostname in groups['database']

    - name: create suplementary group
      ansible.builtin.group:
        name: opsmgr
        state: present
      when: inventory_hostname in groups['proxy'] or inventory_hostname in groups['prod']


    - name: create the users with their secondary group
      ansible.builtin.user:
        name: "{{item.username}}"
        groups: devops
        append: yes
        update_password: on_create  
        password: "{{ pw_developer | password_hash('sha512') }}"
      loop: "{{users}}"
      when:
        - inventory_hostname in groups['database'] or inventory_hostname in groups['test']
        - item.Job == "developer"


    - name: create the users with their secondary group
      ansible.builtin.user:
        name: "{{item.username}}"
        groups: opsmgr
        append: yes
        update_password: on_create
        password: "{{ pw_manager | password_hash('sha512') }}"
      loop: "{{users}}"
      when:
        - inventory_hostname in groups['proxy'] or inventory_hostname in groups['prod']
        - item.Job == "manager"
      

      



    

