---
- name: Install the mariadb package
  ansible.builtin.dnf:
    name: mariadb-server
    state: latest

- name: Open up the firewall port
  ansible.posix.firewalld:
    port: 3306/tcp
    permanent: true
    state: enabled
    immediate: true

- name: Start and enable the service
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Set mysql root user password
  ansible.builtin.expect:
    command: mysql_secure_installation
    responses:
      'Enter current password for root': ''
      'Switch to unix_socket authentication': ''
      'Change the root password?': 'y'
      'New password': "{{ database_password }}"
      'Re-enter new password': "{{ database_password }}" 
      'Remove anonymous users': 'y'
      'Disallow root login remotely': 'y'
      'Remove test database and access to it': 'y'
      'Reload privilege tables now': 'y'      

- name: The configuration file is in place
  ansible.builtin.template:
    src: my.cnf.j2 
    dest: /etc/my.cnf.d/mariadb-server.cnf
  notify: restart mariadb    

