---
# tasks file for roles/apache

- name: Install the httpd packages
  ansible.builtin.dnf:
    name: 
      - httpd
      - firewalld
    state: present

- name: Start and enable the services
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - httpd
    - firewalld

- name: Allow access to httpd
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true

- name: Index.html is in place
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd

  
