# tasks file for roles/sample-apache
- name: Install the required packages
  ansible.builtin.dnf:
    name:
      - httpd
      - mod_ssl
      - php
    state: present

- name: enable services
  ansible.builtin.service:
    name: httpd
    state: started


- name: Configure firewalld to allow http port
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - https
    - http

- name: Create the j2 file
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd
