---
- name: Work with Ansible Facts
  hosts: database
  become: yes
  tasks:
    - name: Ensure the directory exist
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes

    - name: Use copy module to copy content
      ansible.builtin.copy:
        content: "[sample_exam]\nserver_role=mysql\n"
        dest: /etc/ansible/facts.d/custom.fact

