---
- name: install packages 
  hosts: proxy
  become: true
  tasks:
    
    - name: install the proxy packages
      ansible.builtin.dnf:
        name: tcpdump
        state: latest

- name: install packages
  hosts: database
  become: true
  tasks:

    - name: install the database packages
      ansible.builtin.dnf:
        name: lsof
        state: latest         

    
