---
- name: Configure Selinux for webservers
  hosts: webservers
  become: true
  vars:
    selinux_booleans:
      - name: httpd_can_network_connect
        state: true
        persistent: true

  roles:
    - role: rhel-system-roles.selinux
